### PR TITLE
implemented horizontal mode and week number display

### PR DESCRIPTION
**Pull request by vwegert**

### CODE REVIEW

**Comment by vwegert** [comment]
...this should resolve issues #4 and #5

**Comment by BKeyport** [comment]
Actually, I was in the process of re-writing the module myself for expandability. I'll take a look at your code and possibly merge.

**Review by BKeyport — COMMENTED** [review]
This is rather brilliant. Shows how much I have to learn about Javascript. Did you test it for change of start of week, and other languages? 

Edit; I did. It works beautifully. I understand how the code works, too - I'm merging. 

Thank you very much.

**Comment by vwegert** [comment]
> This is rather brilliant. Shows how much I have to learn about Javascript. 

So do I - which is a good sign I believe. Developers become dangerous once they believe they don't have to learn any more.

> Did you test it for change of start of week, and other languages?

In fact I did because my setup is in German with Monday being the first day of the week.

> Edit; I did. It works beautifully. I understand how the code works, too - I'm merging.

Thanks a lot!

**Comment by BKeyport** [comment]
The thanks belong to you, completely.

**Pull request merged**
